general/urls.py
from .views import IndexView, ContactView, TermsAndConditions,CareerView
from django.urls import path


app_name = "general"
urlpatterns = [
    path("", IndexView.as_view(), name = "home"),
    path("contact/", ContactView.as_view(), name = "contact"),
    path("career/", CareerView.as_view(), name = "career"),
    path("terms-and-conditions/", TermsAndConditions.as_view(), name = "tandc"),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("general.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

general/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=50)
    e_mail = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return self.e_mail


class Career(models.Model):
    name = models.CharField(max_length=50)
    e_mail = models.EmailField()
    message = models.TextField()
    resume = models.FileField(upload_to="resumes/")

    def __str__(self):
        return self.e_mail

general/forms.py
from django.forms import ModelForm
from .models import Contact, Career


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
    

class CareerForm(ModelForm):
    class Meta:
        model = Career
        fields = "__all__"

general/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from .forms import ContactForm, CareerForm
from django.urls import reverse_lazy
from django.contrib import messages

class IndexView(TemplateView):
    template_name = "general/index.html"

class ContactView(FormView):
    template_name = "general/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("general:home")
    
    def form_valid(self, form):
        form.save()
        messages.success(self.request,"Submitted Succesfully")
        return super().form_valid(form)

class CareerView(FormView):
    template_name = "general/career.html"
    form_class = CareerForm
    success_url = reverse_lazy("general:home")
    
    def form_valid(self, form):
        form.save()
        messages.success(self.request,"Submitted Succesfully")
        return super().form_valid(form) 
          

class TermsAndConditions(TemplateView):
    template_name = "general/tandc.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>website 2021</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- jquery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js'%}"></script>
</head>
<body>
    <div class="container-fluid px-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand text-uppercase" href="#">Company</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% url 'general:home' as homeurl %}
            <li class="nav-item {% if request.path == homeurl %}active {% endif %}">
              <a class="nav-link {% if request.path == homeurl %}text-success{% endif %}" href="{{ homeurl }}">Home</a>
            </li>
            {% url 'general:career' as careerurl %}
            <li class="nav-item {% if request.path == careerurl %}active{% endif %}">
              <a class="nav-link" href="{{ careerurl }}">Career</a>
            </li>
            {% url 'general:contact' as contacturl %}
            <li class="nav-item {% if request.path == contacturl %}active{% endif %}">
              <a class="nav-link" href="{{ contacturl }}">contact</a>
            </li>
            {% url 'general:tandc' as tandcurl %}
            <li class="nav-item {% if request.path == tandcurl %}active{% endif %}">
            <a class="nav-link" href="{{ tandcurl }}">tandc</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li {% if message.tags%} class="alert alert-{{ message.tags}}" {% endif %}>{{message}}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div> 
<div class="container-fluid px-0"> 
    {% block content %}

    {% endblock %}
</div> 
<div class="container-fluid pt-4 bg-dark">
<div class="row">
  <div class="col-3 text-light">
    <h3>About</h3>
        <hr class="bg-light">
    <p>FAQ</p>
    <p>privacy policy</p>
    <p>about us</p>
    <p>terms and conditions</p>
    <p>RSS Feed</p>
  </div>
  <div class="col-3 text-light">
    <h3>News</h3>
        <hr class="bg-light">
    <p>Travel</p>
    <p>Art</p>
    <p>Business</p>
    <p>sports</p>
    <p>Politics</p>
  </div>
  <div class="col-3 text-light">
    <h3>Features</h3>
        <hr class="bg-light">
    <p>Subscription</p>
    <p>Accessibility</p>
  </div>
  <div class="col-3 text-light">
    <h3>More</h3>
        <hr class="bg-light">
    <p>Newsletter</p>
    <p>Ads</p>
    <p>Sitemap</p>
  </div>
</div>
<div class="text-center py-2 text-light bg-secondary">
  {% now "Y" %} &copy; all rights reserved
</div>
</div>


    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js'%}"></script>
    
    <!-- bootstrapjs
    popper.js src-->
 
</body>
</html>

templates/general/career.html
{% extends "base.html"%}

{% block content %}
<h1 class="text-center pb-5">CAREER</h1>
<div class="container"></div>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row justify-content-center">
            {% csrf_token %}
            <div class="col-4">
                <input class="form-control mb-3" type="text" id="{{ form.name.auto_id }}" name="{{ form.name.html_name }}" placeholder="enter name">
                <div class="text-danger"> {{ form.name.errors }} </div>
            </div>
            <div class="col-4">
                <input class="form-control mb-3" type="email" id="{{ form.e_mail.auto_id }}" name="{{ form.e_mail.html_name }}" placeholder="enter e_mail">
                <div class="text-danger"> {{ form.e_mail.errors }} </div>     
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-8">
                <textarea class="form-control mb-3" id="{{ form.message.auto_id }}" name="{{ form.message.html_name }}" placeholder="enter message" cols="10" rows="5"></textarea>
            </div>
        </div>
        
        <div class="row justify-content-center mb-3">
            <div class="col-4">
                Upload Your Resume
            </div>
            <div class="col-4">
                <input type="file" name={{form.resume.html_name}} id={{ form.resume.auto_id }} class="form-control-file">
                <div class="text-danger"> {{ form.resume.errors }} </div>
            </div>
            

        </div>
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="SEND MESSAGE">
        </div>
        

     </form>
</div>
{% endblock %}

templates/general/contact.html
{% extends "base.html"%}

{% block content %}
<h1>CONTACT US</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <br>
        <br>
        <input class="btn btn-success" type="submit" value="SEND MESSAGE">
    </form>
    
</div>
{% endblock %}

templates/general/index.html
{% extends "base.html" %}

{% load static %}

{% block content %} 


<head>
    <style>
/* .topnav {
    background-color: rgb(33, 61, 104);
    overflow: hidden;
    
}

.topnav a {
    float: left;
    color: #f8fbf8;
    text-align: center;
    padding: 14px 16px;
    font-size: 17px;
  }
  
  .topnav a:hover {
    background-color: rgb(77, 11, 11);
    color: burlywood;
  } */
  
  
    </style>
    
</head>
<body>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/b.png'%}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/c.png'%}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/d.png'%}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    <!-- <div class="topnav">
        <a href="index.html">Home</a>
        <a href="contact.html">Contactus</a>
        <a href="career.html">Career</a>
        <a href="career.html">tandc</a>
    </div>
    <div>
       <img src="{% static 'img/a.jpg'%}" class="img-fluid" >
    </div> -->
</body>

{% endblock %}

templates/general/tandc.html
{% extends "base.html" %}

{% block content %}

<div>
<h2>Terms of Use</h2>
<p class="text-justify">
These Terms and Conditions constitute an agreement (“Agreement”) between you (“you”, “your”, “user”, “Customer”) and the Company.Avocado gumbo artichoke ricebean groundnut tigernut. Daikon kakadu plum water spinach garbanzo eggplant fava bean chard rock melon carrot rutabaga water chestnut broccoli courgette onion. 
</p>
<h2>Eligibility and Identity.</h2>
<p class="text-justify">
To be eligible to use our Services, you must be at least 13 years old. Sorrel jícama tomato silver beet wattle seed black-eyed pea garlic fennel tigernut okra beetroot shallot. Soko shallot melon dandelion bamboo shoot chickpea soybean pumpkin kakadu plum parsley ricebean grape courgette courgette jícama tatsoi. Black-eyed pea gourd tomatillo arugula cucumber celery mustard black-eyed pea cauliflower soybean rutabaga turnip groundnut.
</p>
<h2>Termination</h2>
<p class="text-justify">

You may terminate this Agreement at any time by ceasing all use of the Services and by notifying us. The Company may terminate this Agreement, at any time, without notice to you, if it believes, in its sole judgment, that you have breached or may breach any term or condition of this Agreement. Fennel garlic melon broccoli kohlrabi dulse black-eyed pea chicory watercress shallot bamboo shoot cucumber rutabaga ricebean gourd chickweed gumbo. Burdock fennel sorrel cress collard greens tomato tigernut salad chickweed yarrow water spinach catsear earthnut pea cabbage dulse potato. Onion courgette bitterleaf rutabaga tomatillo tigernut groundnut courgette water spinach tomato. Celery ricebean cabbage salsify caulie watercress cress collard greens potato chard gourd pea sprouts cucumber dulse gram. Leek summer purslane tatsoi catsear celtuce broccoli rabe onion zucchini.

</p>
<h2>Use of Services & Account</h2>
<p class="text-justify">

You represent and warrant that you possess the legal right and ability to enter into this Agreement. You agree not to use the Materials, Content, Services, and your Account for any unlawful or abusive purpose or in any way which interferes with our ability to provide Services to our customers, or which damages our property.Chickpea gourd coriander daikon zucchini lettuce tomatillo sierra leone bologi maize parsnip grape melon kohlrabi welsh onion. Celery wakame corn garlic courgette silver beet cabbage gram amaranth jícama bitterleaf. Ricebean bunya nuts prairie turnip water chestnut artichoke cauliflower watercress gourd cabbage okra broccoli rabe. Burdock leek sorrel radicchio azuki bean collard greens winter purslane broccoli rabe gourd water chestnut pumpkin gumbo. Azuki bean green bean kohlrabi kombu aubergine salsify lotus root turnip lentil radicchio nori eggplant sorrel. 
</p>
<h2>Modification to Service</h2>
<p class="text-justify">

The Company may change, suspend, or discontinue all or any part of the Service at any time, with or without reason. You acknowledge that the operation of the Service may from time to time encounter technical or other problems and may not necessarily continue uninterrupted or without technical or other errors and The Company shall not be responsible to you or others for any such interruptions, errors or problems or an outright discontinuance of the Service. 
</p>
<h2>Intellectual Property Ownership</h2>
<p class="text-justify">

All Materials, Services, Accounts, and content, including, but not limited to, policy information, text, software, music, sound, photographs, video, graphics, the arrangement of text and images, commercially produced information, and other material contained on the Site or through the Services (“Content”), are provided by The Company unless indicated otherwise. Welsh onion tigernut broccoli asparagus brussels sprout jícama eggplant earthnut pea cress chickpea gourd zucchini. Radicchio lentil cucumber groundnut endive kohlrabi winter purslane. Seakale plantain quandong celtuce shallot fennel seakale epazote groundnut dandelion.
</p>
<h2>Privacy</h2>
<p class="text-justify">

Please see our <a href="#">Privacy Policy</a> as set forth on the site.

</p>
<h2>About These Terms</h2>
<p class="text-justify">

These Terms and Conditions are just a sample and are not legally binding. Real Terms of Services do not (usually) contain vegetables...</p>

</div>
{% endblock %}